### ISSUE TITLE
Roadmap for preparing benchmarking datasets

### ISSUE THREAD

**Issue by Zehui127** [bowang-lab/genomic-FM#1]
We will unify the format of existing genetic variants prediction datasets. And write utility functions to convert genetic variants  to DNA sequences which are friendly to foundational models.

Contributions are summarized as the following: 
- Curate datasets for genomic variant predictions to create a benchmark. This will bridge the gap between the evaluation of language-model-style DNA foundational models (HyenaDNA, DNABERT2, ...) and genomic track prediction foundation models (Enformer, BigRNA, ... ) on genomic variants prediction. 
- Develop a post-training (or fine-tuning) method to adopt the autoregressive and masked genomic models to cell type-specific prediction (eQTL and GWAS).
- Analyse the GWAS results with genomic foundation models, which is conventionally done with a series of wet-lab experiments (see review paper for [GWAS](https://www.nature.com/articles/s43586-021-00056-9))
- Extend the SNP prediction to CRISP-KO and (potentially Disease Subtype prediction?)

```
Potential Direction: The tasks in our dataset have a similar format, where the inputs are mutated DNA sequences and the reference genome, and the output is a real value indicating whether this mutation is diseases related (for clinVar it is a discrete label, for CRISP-KO it is the fitness score, for cell passport it is a discrete label). At the same time,  GTEx, CRISP-KO,  and cell passports are tissue-specific, while clinvar is not. Is it possible to unify all the tasks into the same format, where we have the (DNA, text) as the input, and try to predict the target? If it is possible, our model will be the true Foundation Model for genomics. 
One related note on this, the real challenge of the genetic foundation model is
- The model should be able to deal with variable length input
- The model should be able to do contextual prediction with various cell types
```

## Datasets
For classification Task:
- [x] ClinVar

| Data Source | Description | Number of Variants | Available Metadata |
|-------------|-------------|--------------------|--------------------|
|  ClinVar | Short variants in ClinVar ([link](https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/clinvar_20240206.vcf.gz)) | 2.3 million | Influenced gene names, Disease names, Influence (Benign, Likely benign, Uncertain significance, Likely pathogenic, Pathogenic) |
| genomAD| Reference population databases (e.g. [link](https://arxiv.org/pdf/2107.11458.pdf))| Total SNVs: 786,500,648 Total InDels: 122,583,462| No Benign or Pathegentic labels Available|

For Regression Tasks:

- [x] eQTL fine-mapping: Each variant -> P-value for gene X in tissue Y

| Data Source     | Description | Size                               | Data Format           |
|-----------------|-------------|------------------------------------|----------------------|
| GTE x Portal    | GTEx_v8 ([link](https://console.cloud.google.com/storage/browser/gtex-resources/GTEx_Analysis_v8_QTLs?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)) | 690GB (google cloud account needed) | Need to be checked   |

Gene Level CRISPR-KO and Cancer related Genetic Variants
Gene Mapping File: [gene-chr:pos mapping](https://www.gencodegenes.org/human/)

- [x]  Score Project

| Data Source     | Description | Size                               | Data Format           |
|-----------------|-------------|------------------------------------|----------------------|
| Score Project | The influence of Gene KO across different cell lines as measured by fitness score([link](https://score.depmap.sanger.ac.uk/downloads))|350MB | gene names x cell lines matrix |
| Mutation GWS | Genetic variants in cancer cell lines (SNPs + indel) | around 1 GB |  similar to clinvar but with labels (cancer driver, cancer predisposition variant, Normal Panel GermLine)|

## Utility Functions
- [x] Mapping genetic variants file to DNA sequences [reference](https://colab.research.google.com/github/deepmind/deepmind_research/blob/master/enformer/enformer-usage.ipynb)
- [x] Unify the format of clinvar, cell passport, gene-ko, and GTE-x

### List of Models
- [ ] Based Line Model: CNN+Max Pooling
- [ ] Genomic Track Foundational Model: Enformer
- [ ] Genomic Track Foundation Model: BigRNA
- [x] Autoregressive Model: HyenaDNA
- [x] Autoregressive Model: NeuleotideTransformer
- [x] Autoregressive Model: [GENA-LM](https://github.com/AIRI-Institute/GENA_LM?tab=readme-ov-file)
- [ ] Autoregressive Model: [DNAGPT](https://github.com/maris205/dnagpt)
- [x] Masked Genomic Model: DNABERT (Optional)
- [x] Masked Genomic Model: DNABERT2
- [ ] Masked Genomic Model: [GPN](https://github.com/songlab-cal/gpn) (GPN-MSA could be challenging to benchmark as we don't have the alignment sequences for all the datasets.)
